- hosts: all
  become: true
  become_user: root
  roles:
    - { role: system, tags: system }
    - { role: ssh, tags: ssh }
    - { role: http, tags: http }
    - { role: bgp, tags: bgp }
    - { role: tls, when: inventory_hostname == "ams01.atr.ilams.net", tags: tls }
