- name: set hostname
  copy:
    content: "{{ inventory_hostname }}\n"
    dest: /etc/myname
    mode: 0644
    owner: root
    group: wheel

- name: set timezone
  file:
    state: link
    src: /usr/share/zoneinfo/Etc/UTC
    path: /etc/localtime
    force: yes

- name: "upload pf rules"
  template:
    src: pf.conf.j2
    dest: "/etc/pf.conf"
    mode: 0600
  notify:
    - reload pf

- name: ensure pf is enabled
  service: name=pf enabled=yes

- name: set install url
  copy:
    content: "https://ftp.openbsd.org/pub/OpenBSD\n"
    dest: /etc/installurl
    mode: 0644

- name: forward root mail to job
  copy:
    content: "job@instituut.net\n"
    dest: /root/.forward
    mode: 0644

- name: copy ntpd.conf
  template:
    src: ntpd.conf.j2
    dest: "/etc/ntpd.conf"
    owner: root
    group: wheel
    mode: 0644
  notify: restart ntpd
   
- name: ntpd rc flags
  lineinfile:
    dest: /etc/rc.conf.local
    regexp: "^ntpd_flags="
    line: 'ntpd_flags="-s"'
    create: yes
  notify: restart ntpd

- name: start ntpd
  service: name=ntpd state=started
